-- V1__location_schema.sql
-- Location service schema: PostGIS zones, geocode cache, trip traces

-- Enable PostGIS extension (requires postgis/postgis Docker image for tests)
CREATE EXTENSION IF NOT EXISTS postgis;

-- Geofence zones (OPERATING, SURGE, AIRPORT, RESTRICTED, PICKUP_ONLY)
CREATE TABLE zones (
    id            UUID         PRIMARY KEY,  -- ULID generated by application
    country_code  CHAR(2)      NOT NULL,
    city_id       UUID         NOT NULL,     -- references operating_cities in country-config-service DB (no FK)
    name          VARCHAR(100) NOT NULL,
    boundary      GEOGRAPHY(POLYGON, 4326) NOT NULL,
    type          VARCHAR(20)  NOT NULL,
    config        JSONB        DEFAULT '{}',
    is_active     BOOLEAN      DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_zones_city_type ON zones(city_id, type);
CREATE INDEX idx_zones_boundary ON zones USING GIST(boundary);

-- Geocode cache (30-day TTL, cache-through pattern)
CREATE TABLE geocode_cache (
    id            UUID         PRIMARY KEY,  -- ULID generated by application
    country_code  CHAR(2)      NOT NULL,
    query_hash    VARCHAR(64)  UNIQUE NOT NULL,
    query         TEXT         NOT NULL,
    latitude      NUMERIC(10,7) NOT NULL,
    longitude     NUMERIC(10,7) NOT NULL,
    address       TEXT,
    provider      VARCHAR(30),
    hit_count     INTEGER      DEFAULT 1,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ
);

CREATE INDEX idx_geocache_hash ON geocode_cache(query_hash);

-- Completed trip GPS traces (flushed from Redis on ride completion)
CREATE TABLE trip_traces (
    id               UUID         PRIMARY KEY,  -- ULID generated by application
    ride_id          UUID         NOT NULL UNIQUE,
    country_code     CHAR(2)      NOT NULL,
    driver_id        UUID         NOT NULL,
    trace            JSONB        NOT NULL,     -- array of {lat, lng, ts} points
    distance_metres  INT,
    started_at       TIMESTAMPTZ,
    completed_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_trip_traces_ride ON trip_traces(ride_id);
CREATE INDEX idx_trip_traces_driver ON trip_traces(driver_id);
