-- Auth service schema
-- ULIDs are generated by the application (UlidGenerator), NOT the database

CREATE TABLE auth_users (
    id             UUID         PRIMARY KEY,
    phone_number   VARCHAR(20)  UNIQUE NOT NULL,
    country_code   CHAR(2)      NOT NULL,
    role           VARCHAR(20)  NOT NULL,
    is_active      BOOLEAN      NOT NULL DEFAULT true,
    phone_verified BOOLEAN      NOT NULL DEFAULT false,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_auth_users_phone ON auth_users(phone_number);
CREATE INDEX idx_auth_users_country ON auth_users(country_code);

CREATE TABLE otp_codes (
    id           UUID         PRIMARY KEY,
    phone_number VARCHAR(20)  NOT NULL,
    code         VARCHAR(6)   NOT NULL,
    expires_at   TIMESTAMPTZ  NOT NULL,
    used         BOOLEAN      NOT NULL DEFAULT false,
    attempts     INT          NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_otp_phone ON otp_codes(phone_number);
CREATE INDEX idx_otp_expires ON otp_codes(expires_at);

-- Refresh token blocklist (Redis is primary, DB is fallback for persistence)
CREATE TABLE revoked_tokens (
    jti        VARCHAR(64)  PRIMARY KEY,
    revoked_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_revoked_tokens_expires ON revoked_tokens(expires_at);
