-- Country config service schema
-- ULIDs are generated by the application (UlidGenerator), NOT the database
-- country_configs uses a natural key (code CHAR(2)), not UUID

CREATE TYPE country_status AS ENUM ('ACTIVE', 'COMING_SOON', 'INACTIVE');

CREATE TABLE country_configs (
    code              CHAR(2)        PRIMARY KEY,
    name              VARCHAR(100)   NOT NULL,
    status            country_status NOT NULL DEFAULT 'COMING_SOON',

    -- Locale
    default_locale    VARCHAR(10)    NOT NULL,
    supported_locales TEXT[]         NOT NULL,
    date_format       VARCHAR(20)   NOT NULL DEFAULT 'DD/MM/YYYY',
    distance_unit     VARCHAR(5)    NOT NULL DEFAULT 'km',
    time_format       VARCHAR(5)    NOT NULL DEFAULT '12h',

    -- Currency
    currency_code     VARCHAR(3)     NOT NULL,
    currency_symbol   VARCHAR(5)     NOT NULL,
    minor_units       INT            NOT NULL DEFAULT 0,
    display_format    VARCHAR(20)    NOT NULL,

    -- Phone
    phone_prefix      VARCHAR(5)     NOT NULL,

    -- Payment
    cash_enabled            BOOLEAN  NOT NULL DEFAULT true,
    subscription_aggregator VARCHAR(50),

    -- Notification providers (per-country switching)
    sms_provider      VARCHAR(30)    NOT NULL DEFAULT 'AFRICASTALKING',
    push_provider     VARCHAR(30)    NOT NULL DEFAULT 'FCM',

    -- Regulatory
    regulatory_authority    VARCHAR(100),
    trip_reporting_required BOOLEAN  NOT NULL DEFAULT false,
    data_retention_days     INT      NOT NULL DEFAULT 365,

    -- Feature flags (JSONB for flexibility)
    features JSONB NOT NULL DEFAULT '{
        "ussdEnabled": false,
        "deliveryEnabled": false,
        "scheduledRidesEnabled": false,
        "surgeEnabled": false,
        "loyaltyEnabled": true,
        "corporateAccountsEnabled": false,
        "driverReferralsEnabled": true
    }',

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE vehicle_type_configs (
    id                   UUID          PRIMARY KEY,
    country_code         CHAR(2)       NOT NULL REFERENCES country_configs(code),
    vehicle_type         VARCHAR(30)   NOT NULL,
    display_name         VARCHAR(50)   NOT NULL,
    max_passengers       INT           NOT NULL,
    icon_key             VARCHAR(50),
    is_active            BOOLEAN       NOT NULL DEFAULT true,

    -- Pricing (all monetary values as NUMERIC, never float)
    base_fare            NUMERIC(12,2) NOT NULL,
    per_km               NUMERIC(12,2) NOT NULL,
    per_minute           NUMERIC(12,2) NOT NULL,
    minimum_fare         NUMERIC(12,2) NOT NULL,
    cancellation_fee     NUMERIC(12,2) NOT NULL DEFAULT 0,
    surge_multiplier_cap NUMERIC(4,2)  NOT NULL DEFAULT 2.5,

    required_docs TEXT[] NOT NULL DEFAULT '{}',

    UNIQUE(country_code, vehicle_type)
);

CREATE INDEX idx_vehicle_type_configs_country ON vehicle_type_configs(country_code);

CREATE TABLE operating_cities (
    id                     UUID          PRIMARY KEY,
    country_code           CHAR(2)       NOT NULL REFERENCES country_configs(code),
    city_id                VARCHAR(50)   NOT NULL,
    name                   VARCHAR(100)  NOT NULL,
    timezone               VARCHAR(50)   NOT NULL,
    status                 VARCHAR(20)   NOT NULL DEFAULT 'COMING_SOON',
    center_lat             DOUBLE PRECISION NOT NULL,
    center_lng             DOUBLE PRECISION NOT NULL,
    radius_km              INT           NOT NULL,

    -- Per-city provider switching (location module reads these)
    geocoding_provider     VARCHAR(30)   NOT NULL DEFAULT 'GOOGLE',
    routing_provider       VARCHAR(30)   NOT NULL DEFAULT 'GOOGLE',
    autocomplete_provider  VARCHAR(30)   NOT NULL DEFAULT 'GOOGLE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE(country_code, city_id)
);

CREATE INDEX idx_operating_cities_country ON operating_cities(country_code);

CREATE TABLE payment_method_configs (
    id           UUID        PRIMARY KEY,
    country_code CHAR(2)     NOT NULL REFERENCES country_configs(code),
    method_id    VARCHAR(30) NOT NULL,
    provider     VARCHAR(50) NOT NULL,
    is_enabled   BOOLEAN     NOT NULL DEFAULT true,
    display_name VARCHAR(50) NOT NULL,
    icon_key     VARCHAR(50),

    UNIQUE(country_code, method_id)
);

CREATE INDEX idx_payment_method_configs_country ON payment_method_configs(country_code);

CREATE TABLE required_driver_documents (
    id            UUID         PRIMARY KEY,
    country_code  CHAR(2)      NOT NULL REFERENCES country_configs(code),
    document_type VARCHAR(50)  NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    is_mandatory  BOOLEAN      NOT NULL DEFAULT true,

    UNIQUE(country_code, document_type)
);

CREATE INDEX idx_required_driver_documents_country ON required_driver_documents(country_code);
