-- User service schema
-- users.id is NOT auto-generated — it matches the auth-service AuthUser.id exactly
-- saved_places.id is generated by the application (UlidGenerator), NOT the database

CREATE TABLE users (
    id                       UUID         PRIMARY KEY,
    country_code             CHAR(2)      NOT NULL,
    full_name                VARCHAR(150) NOT NULL,
    email                    VARCHAR(255),
    profile_photo_url        VARCHAR(500),
    preferred_locale         VARCHAR(10),
    preferred_payment_method VARCHAR(30),
    is_active                BOOLEAN      NOT NULL DEFAULT true,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE saved_places (
    id           UUID         PRIMARY KEY,
    user_id      UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    label        VARCHAR(50)  NOT NULL,
    address      VARCHAR(300) NOT NULL,
    latitude     DOUBLE PRECISION NOT NULL,
    longitude    DOUBLE PRECISION NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_saved_places_user ON saved_places(user_id);
