-- V1__driver_schema.sql
-- Driver service schema: profiles, vehicles, documents, status audit log

CREATE TABLE drivers (
    id                UUID         PRIMARY KEY,  -- same UUID as auth-service, ULID generated by application
    country_code      CHAR(2)      NOT NULL,
    full_name         VARCHAR(150) NOT NULL,
    email             VARCHAR(255),
    profile_photo_url VARCHAR(500),
    status            VARCHAR(30)  NOT NULL DEFAULT 'PENDING_APPROVAL',
    rejection_reason  TEXT,
    approved_at       TIMESTAMPTZ,
    approved_by       UUID,
    trip_count        INT          NOT NULL DEFAULT 0,
    last_trip_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_driver_status ON drivers(status);
CREATE INDEX idx_driver_country ON drivers(country_code, status);

CREATE TABLE driver_vehicles (
    id              UUID         PRIMARY KEY,  -- ULID generated by application
    driver_id       UUID         NOT NULL REFERENCES drivers(id),
    country_code    CHAR(2)      NOT NULL,
    vehicle_type    VARCHAR(30)  NOT NULL,
    make            VARCHAR(50),
    model           VARCHAR(50),
    year            INT,
    plate_number    VARCHAR(20)  NOT NULL,
    color           VARCHAR(30),
    is_active       BOOLEAN      NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE(driver_id, plate_number)
);

CREATE INDEX idx_vehicles_driver ON driver_vehicles(driver_id);

CREATE TABLE driver_documents (
    id               UUID         PRIMARY KEY,  -- ULID generated by application
    driver_id        UUID         NOT NULL REFERENCES drivers(id),
    country_code     CHAR(2)      NOT NULL,
    document_type    VARCHAR(50)  NOT NULL,
    file_url         VARCHAR(500) NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    rejection_reason TEXT,
    verified_by      UUID,
    verified_at      TIMESTAMPTZ,
    expires_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE(driver_id, document_type)
);

CREATE INDEX idx_documents_driver ON driver_documents(driver_id);

CREATE TABLE driver_status_log (
    id           UUID         PRIMARY KEY,  -- ULID generated by application
    driver_id    UUID         NOT NULL REFERENCES drivers(id),
    country_code CHAR(2)      NOT NULL,
    from_status  VARCHAR(30),
    to_status    VARCHAR(30)  NOT NULL,
    reason       TEXT,
    changed_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_status_log_driver ON driver_status_log(driver_id);
